pipeline {
  agent {
    docker { image 'nginx:1.27.0' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'nginx -v'
      }
    }
    stage('start nginx'){
      steps {
        sh ''' apt install systemd
        systemctl start nginx
        '''
      }
    }
    
  }
}
