pipeline {
  agent {
    docker { image 'nginx:1.27.0' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'nginx -v'
      }
    }
    stage('start'){
      steps {
        sh '''service start nginx'''
      }
    }
    stage('webpage') {
      steps {
        sh '''cd /var/www/html
        sudo rm -rf index.html
        nano index.html
        "hello world"
        '''
      }
    }
  }
}
