pipeline {
  agent {
    docker { image 'nginx:1.27.0' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'nginx -v'
      }
    }
    stage('start nginx'){
      steps {
        sh 'sudo apt install systemd
        sudo systemctl start nginx
        '
      }
    }
    stage('webpage') {
      steps {
        / Access the webpage URL 
        sh 'curl http://localhost'
      }
    }
  }
}
